server:
  port: 8888

spring:
  application:
    name: config-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dduckmane/git-local-repo.git
#          username: private 시에는 입력
#          password:

management:
  endpoint:
    web:
      exposure:
        include: health, busrefresh
